SimpleBlogCore.WebApp/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace SimpleBlogCore.WebApp.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = "Admin")]
	public class HomeController : Controller
	{
		public async Task<IActionResult> Index()
		{
			return View();
		}
	}
}

SimpleBlogCore.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SimpleBlogCore.Domain.Interfaces;
using SimpleBlogCore.WebApp.Models;
using System.Diagnostics;
using System.Threading.Tasks;

namespace SimpleBlogCore.WebApp.Controllers
{
	public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IPostAsyncRepository repository;

        public HomeController(ILogger<HomeController> logger, IPostAsyncRepository repository)
        {
            _logger = logger;
            this.repository = repository;
        }

        public async Task<IActionResult> Index(int? page)
        {
            var pagedListViewModel = await PostsPagedListViewModel.BuildDefaultModel(repository, page ?? 1);
            ViewBag.Title = "Latest posts";
            return View(pagedListViewModel);
        }

        public async Task<IActionResult> GetByTag(string tagName, int? page) 
        {
            var pagedListViewModel = await PostsPagedListViewModel.BuildModelForTag(repository, page ?? 1, tagName);
            ViewBag.Title = $"Latest posts tagged in «{tagName}»";
            return View("Index", pagedListViewModel);
        }

        public async Task<IActionResult> GetBySearch(string search, int? page)
        {
            var pagedListViewModel = await PostsPagedListViewModel.BuildModelForSearch(repository, page ?? 1, search);
            ViewBag.Title = $"Latest posts with the searched word «{search}»";
            return View("Index", pagedListViewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public ActionResult Aboutme()
        {
            return View();
        }

        public ActionResult Contacts()
        {
            return View();
        }
    }
}

SimpleBlogCore.WebApp/ViewComponents/SidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SimpleBlogCore.Domain.Entities;
using SimpleBlogCore.Domain.Interfaces;
using SimpleBlogCore.WebApp.Models;

namespace SimpleBlogCore.WebApp.ViewComponents
{
	public class SidebarViewComponent : ViewComponent
	{
		private readonly IPostAsyncRepository _postRepository;
		private readonly IAsyncRepository<Tag> _tagRepository;

		public SidebarViewComponent(IPostAsyncRepository postRepository, IAsyncRepository<Tag> tagRepository)
		{
			_postRepository = postRepository;
			_tagRepository = tagRepository;
		}

		public IViewComponentResult Invoke()
		{
			var sidebarViewModel = new SidebarViewModel(_postRepository, _tagRepository);
			return View(sidebarViewModel);
		}
	}
}

SimpleBlogCore.WebApp/Views/Home/Aboutme.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "About me";
}

<div class="row">
    <div id="main" class="s-content__main large-8 column">

        <h2>About me</h2>

        <p>
            <a href="#">
                <img class="h-pull-left" alt="sample-image" src="https://picsum.photos/200/300">
            </a>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum.Cras id urna. Morbi
            tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo. Donec mattis,
            purus nec placerat bibendum, dui pede condimentum odio, ac blandit ante orci ut diam. Cras fringilla magna.
            Phasellus suscipit, leo a pharetra condimentum, lorem tellus eleifend magna, eget fringilla velit magna id
            neque posuere nunc justo tempus leo.
        </p>

        <p>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna.
            Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo.
            Donec mattis, purus nec placerat bibendum, dui pede condimentumodio, ac blandit ante orci ut diam.
        </p>

        <p>
            A <a href="#">link</a>,
            <abbr title="this really isn't a very good description">abbrebation</abbr>,
            <strong>strong text</strong>,
            <em>em text</em>,
            <del>deleted text</del>, and
            <mark>this is a mark text.</mark>
            <code>.code</code>
        </p>
    </div>

    @await Component.InvokeAsync("Sidebar")
</div>

SimpleBlogCore.WebApp/Views/Home/Contacts.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Contacts";
}

<div class="row">
    <div id="main" class="s-content__main large-8 column">
        <h2>Contact with me</h2>

        <form>
            <div>
                <label for="sampleInput">Your email</label>
                <input class="h-full-width" type="email" placeholder="test@mailbox.com" id="sampleInput">
            </div>
            <div>
                <label for="sampleRecipientInput">Reason for contacting</label>
                <div class="ss-custom-select">
                    <select class="h-full-width" id="sampleRecipientInput">
                        <option value="Option 1">Questions</option>
                        <option value="Option 2">Report</option>
                        <option value="Option 3">Others</option>
                    </select>
                </div>
            </div>

            <label for="exampleMessage">Message</label>
            <textarea class="h-full-width" placeholder="Your message" id="exampleMessage"></textarea>

            <label class="h-add-bottom">
                <input type="checkbox">
                <span class="label-text">Send a copy to yourself</span>
            </label>

            <input class="btn--primary h-full-width" type="submit" value="Submit">
        </form>
    </div>

    @await Component.InvokeAsync("Sidebar")
</div>

SimpleBlogCore.WebApp/Views/Home/Index.cshtml
@model PostsPagedListViewModel
@using X.PagedList.Mvc.Core;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = ViewBag.Title;
}
<div class="row">
    <div id="main" class="s-content__main large-8 column">

        <h2>@ViewBag.Title</h2>

        @if (Model.Posts.Any())
        {
            foreach (var post in Model.Posts)
            {
                <partial name="_PostPreviewPartial" model="post" />
            }
        }
        else
        {
            <p>
                Posts not found
                <img id="sad-face" src="https://emojipedia-us.s3.amazonaws.com/thumbs/72/google/133/disappointed-face_1f61e.png" alt="😞" title="Sad Face" width="72" height="72">
            </p>
        }
    </div>

    @await Component.InvokeAsync("Sidebar")
</div>

@Html.PagedListPager(Model.Posts, page => Url.Action("Index", "Home", new { page = page }), new CustomPagedListRenderOptions())