SimpleBlogCore.WebApp/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace SimpleBlogCore.WebApp.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = "Admin")]
	public class HomeController : Controller
	{
		public async Task<IActionResult> Index()
		{
			return View();
		}
	}
}

SimpleBlogCore.WebApp/Areas/Admin/Controllers/TagController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimpleBlogCore.Domain.Entities;
using SimpleBlogCore.Domain.Interfaces;
using SimpleBlogCore.WebApp.Models;
using System;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace SimpleBlogCore.WebApp.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = "Admin")]
	public class TagController : Controller
	{
		private readonly IAsyncRepository<Tag> tagRepository;

		public TagController(IAsyncRepository<Tag> tagRepository)
		{
			this.tagRepository = tagRepository;
		}

		public async Task<IActionResult> GetAll()
		{
			var tags = (await tagRepository.GetAll()).Select(t => new TagViewModel(t));

			return Json(new { data = tags.ToArray() }, new JsonSerializerOptions {
				WriteIndented = true,
			});
		}

		[HttpPost]
		public async Task<IActionResult> Delete(Guid tagId)
		{
			await tagRepository.RemoveById(tagId);
			return Ok();
		}

		public IActionResult Add()
		{
			return View(new TagViewModel());
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Add(TagViewModel tagViewModel)
		{
			if (!ModelState.IsValid)
			{
				return View(tagViewModel);
			}

			var tag = tagViewModel.GetEntity();
			await tagRepository.Add(tag);

			return RedirectToAction("Index", "Home", new { Area = "Admin" });
		}

		public async Task<IActionResult> Edit(Guid id)
		{
			var tag = await tagRepository.GetById(id);
			return View(new TagViewModel(tag));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(TagViewModel tagViewModel)
		{
			if (!ModelState.IsValid)
			{
				return View(tagViewModel);
			}

			var tag = await tagRepository.GetById(tagViewModel.Id.Value);
			tagViewModel.Update(tag);
			await tagRepository.Update(tag);

			return RedirectToAction("Index", "Home", new { Area = "Admin" });
		}
	}
}

SimpleBlogCore.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SimpleBlogCore.Domain.Interfaces;
using SimpleBlogCore.WebApp.Models;
using System.Diagnostics;
using System.Threading.Tasks;

namespace SimpleBlogCore.WebApp.Controllers
{
	public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IPostAsyncRepository repository;

        public HomeController(ILogger<HomeController> logger, IPostAsyncRepository repository)
        {
            _logger = logger;
            this.repository = repository;
        }

        public async Task<IActionResult> Index(int? page)
        {
            var pagedListViewModel = await PostsPagedListViewModel.BuildDefaultModel(repository, page ?? 1);
            ViewBag.Title = "Latest posts";
            return View(pagedListViewModel);
        }

        public async Task<IActionResult> GetByTag(string tagName, int? page) 
        {
            var pagedListViewModel = await PostsPagedListViewModel.BuildModelForTag(repository, page ?? 1, tagName);
            ViewBag.Title = $"Latest posts tagged in «{tagName}»";
            return View("Index", pagedListViewModel);
        }

        public async Task<IActionResult> GetBySearch(string search, int? page)
        {
            var pagedListViewModel = await PostsPagedListViewModel.BuildModelForSearch(repository, page ?? 1, search);
            ViewBag.Title = $"Latest posts with the searched word «{search}»";
            return View("Index", pagedListViewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public ActionResult Aboutme()
        {
            return View();
        }

        public ActionResult Contacts()
        {
            return View();
        }
    }
}

SimpleBlogCore.WebApp/Areas/Admin/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Manage";
}

<div class="row">
    <div id="main" class="s-content__main large-12 column">

        <h2>Manage</h2>

        <div id="tabs">
            <ul>
                <li class="tabs" data-source="@Url.Action("GetAll", "Tag", new { Area = "Admin"})" data-table="tags-table">
                    <a href="#tab-tags">Tags</a>
                </li>
                <li class="tabs" data-source="@Url.Action("GetAll", "Post", new { Area = "Admin"})" data-table="posts-table">
                    <a href="#tab-posts">Posts</a>
                </li>
            </ul>

            <div id="tab-tags">

                <a asp-action="Add"
                   asp-controller="Tag"
                   asp-area="Admin"
                   class="btn btn--primary btn-action">
                    Add
                </a>

                <table id="tags-table" class="display cell-border general-table" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Created</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                </table>
            </div>

            <div id="tab-posts" style="padding: 1em 1em;">

                <a asp-action="Add"
                   asp-controller="Post"
                   asp-area="Admin"
                   class="btn btn--primary btn-action">
                    Add
                </a>

                <table id="posts-table" class="display cell-border general-table" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Title</th>
                            <th>Created</th>
                            <th>Last modified</th>
                            <th>Tags</th>
                            <th>Is published</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                </table>
            </div>

        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript" src="~/js/DataTables/datatables.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="~/js/moment.js"></script>

    <script type="text/javascript">
        $(function () {
            $(".tabs").click(function () {
                var tableId = "#" + $(this).data("table");
                var source = $(this).data("source");
                switch (tableId) {
                    case "#tags-table":
                        initiateTagsTable(tableId, source);
                        break;
                    case "#posts-table":
                        initiatePostsTable(tableId, source);
                        break;
                }
            });

            function initiatePostsTable(tableId, source) {
                $(tableId).DataTable({
                    ajax: source,
                    destroy: true,
                    searching: true,
                    lengthChange: true,
                    paging: true,
                    responsive: true,
                    createdRow: function (row, data) {
                        if (!data.IsPublished) {
                            $(row).find('td').css({ 'background-color': '#ccc' })
                        }
                    },
                    columns: [
                        {
                            data: null,
                            render: function (data, type, full, meta) {
                                return meta.row + 1;
                            },
                            searchable: false,
                        },
                        {
                            data: 'Title',
                            name: 'Title',
                            render: function (data, type, full) {
                                return `<a href="@Url.Action("Get", "Post", new { Area = "" })/${full.Id}">${data}</a>`;
                            }
                        },
                        {
                            data: 'Created',
                            name: 'Created',
                            render: function (data) {
                                return moment(data).format('DD/MM/YYYY HH:mm');
                            }
                        },
                        {
                            data: 'LastModified',
                            name: 'LastModified',
                            render: function (data) {
                                return data ? moment(data).format('DD/MM/YYYY HH:mm') : null;
                            }
                        },
                        {
                            data: 'Tags',
                            name: 'Tags',
                            render: function (tags) {
                                var tagLinks = tags.map(t =>
                                    `<a href="@Url.Action("GetByTag", "Home", new { Area = "" })?tagName=${escape(t.Name)}">
                                        ${t.Name}
                                    </a>`);
                                return tagLinks.join(', ');
                            }
                        },
                        {
                            data: 'IsPublished',
                            name: 'IsPublished',
                            searchable: false,
                            render: function (isPublished) {
                                return isPublished ? "Yes" : "No";
                            }
                        },
                        {
                            data: null,
                            name: 'Actions',
                            searchable: false,
                            orderable: false,
                            render: function (data, type, full) {
                                return `<a href="@Url.Action("Edit", "Post", new { Area = "Admin" })/${full.Id}" class="btn h-full-width btn-action edit">Edit</a>
                                        <a class="btn h-full-width btn-action delete" data-id="${full.Id}">Delete</a>
                                        <a class="btn h-full-width btn-action publish" data-id="${full.Id}">${full.IsPublished ? "Don't publish" : "Publish"}</a>`;

                            }
                        },
                    ],
                    drawCallback: function () {
                        $(this).off("click");

                        var tableApi = this.api();
                        $(this).click(e => {
                            var target = $(e.target);
                            if (target.hasClass('delete')) {
                                e.preventDefault();
                                if (confirm("Do you really want to delete the post?")) {
                                    $.ajax({
                                        url: "@Url.Action("Delete", "Post", new { Area = "Admin"})",
                                        method: "POST",
                                        data: { postId: target.data("id") },
                                        success: function () {
                                            tableApi.ajax.reload(null, false);
                                        }
                                    });
                                }
                            } else if (target.hasClass('publish')) {
                                $.ajax({
                                    url: "@Url.Action("PublishToggle", "Post", new { Area = "Admin"})",
                                    method: "POST",
                                    data: { postId: target.data("id") },
                                    success: function () {
                                        tableApi.ajax.reload(null, false);
                                    }
                                });
                            }
                        });
                    }
                });
            }

            function initiateTagsTable(tableId, source) {
                $(tableId).DataTable({
                    ajax: source,
                    destroy: true,
                    searching: true,
                    lengthChange: true,
                    paging: true,
                    responsive: true,
                    columns: [
                        {
                            data: null,
                            render: function (data, type, full, meta) {
                                return meta.row + 1;
                            },
                            searchable: false,
                        },
                        {
                            data: 'Name',
                            name: 'Name',
                            render: function (data) {
                                return `<a href="@Url.Action("GetByTag", "Home", new { Area = "" })?tagName=${escape(data)}">
                                            ${data}
                                        </a>`;
                            }
                        },
                        {
                            data: 'Description',
                            name: 'Description',
                            render: function (data) {
                                return data;
                            }
                        },
                        {
                            data: 'Created',
                            name: 'Created',
                            render: function (data) {
                                return moment(data).format('DD/MM/YYYY HH:mm');
                            }
                        },
                        {
                            data: null,
                            name: 'Actions',
                            searchable: false,
                            orderable: false,
                            render: function (data, type, full) {
                                return `<a href="@Url.Action("Edit", "Tag", new { Area = "Admin" })/${full.Id}" class="btn h-full-width btn-action edit">Edit</a>
                                        <a class="btn h-full-width btn-action delete" data-id="${full.Id}">Delete</a>`
                            }
                        },
                    ],
                    drawCallback: function () {
                        $(this).off("click");

                        var tableApi = this.api();
                        $(this).click(e => {
                            var target = $(e.target);
                            if (target.hasClass('delete')) {
                                e.preventDefault();
                                if (confirm("Do you really want to delete the tag?")) {
                                    $.ajax({
                                        url: "@Url.Action("Delete", "Tag", new { Area = "Admin"})",
                                        method: "POST",
                                        data: { tagId: target.data("id") },
                                        success: function () {
                                            tableApi.ajax.reload(null, false);
                                        }
                                    });
                                }
                            }
                        });
                    }
                });
            }

            initiateTagsTable("#tags-table", "@Url.Action("GetAll", "Tag", new { Area = "Admin"})");

            $("#tabs").tabs();
        });
    </script>
}